export const ciudad  = [
    {
        codigo:1,
        descripcion:'Cali'
    },
    {
        codigo:2,
        descripcion:'Dagua'
    },
    {
        codigo:3,
        descripcion:'Buenaventura'
    },
    {
        codigo:4,
        descripcion:'Yumbo'
    },
    {
        codigo:5,
        descripcion:'Rozo'
    },
    {
        codigo:6,
        descripcion:'Jamundi'
    }
]